# Site settings
title: ILT
email: samdutton@gmail.com
description: >
  ILT documents.
baseurl: "/content"
url: "https://github.com/samdutton/ilt"
twitter_username: sw12
github_username:  samdutton
source: content
destination: jekyll/_site

# Build settings
markdown: kramdown
