baseurl: /ilt
description: >
  ILT documents.
email: samdutton@gmail.com
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
github_username:  samdutton
title: ILT
twitter_username: sw12
url: "https://github.com/samdutton/ilt"
