baseurl: /ilt
description: >
  ILT documents.
email: samdutton@gmail.com
gems:
  - jekyll-sitemap
github_username:  samdutton
markdown: kramdown
title: ILT
twitter_username: sw12
url: "https://github.com/samdutton/ilt"
